config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users, only: :show
  resources :event_attendee, only: :create
  resources :invitations, only: [ "create", "destroy" ]
  delete :event_attendee, to: "event_attendee#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :location, presence: true
  validates :event_date, presence: true
  belongs_to :creator, class_name: "User"
  has_many :event_attendees, foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :event_attendees, source: :attendee
  has_many :invitations, foreign_key: "invitation_event_id", dependent: :destroy
  has_many :invited_people, through: :invitations, source: :invited_user

  scope :past, -> { where("event_date < ?", Time.now) }
  scope :future, -> { where("event_date >= ?", Time.now) }

  enum :visibility, { private_event: 0, public_event: 1 }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"
  validates_uniqueness_of :attendee_id, scope: :attended_event_id
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitation_event, class_name: "Event"
  belongs_to :invited_user, class_name: "User"
  validates_uniqueness_of :invited_user_id, scope: :invitation_event_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendees, foreign_key: "attendee_id", dependent: :destroy
  has_many :attended_events, through: :event_attendees, source: :attended_event
  has_many :invitations, foreign_key: "invited_user_id", dependent: :destroy
  has_many :invitations_events, through: :invitations, source: :invitation_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/event_attendee_controller.rb
class EventAttendeeController < ApplicationController
  before_action :authenticate_user!
  def create
    @event = event_params
    @attendance = current_user.event_attendees.build(attended_event_id: @event)
    if @attendance.save
      if @invitation = current_user.invitations.where(invitation_event_id: @event).first
        @invitation.destroy
      end
      flash[:notice] = "Successfully joined Event!"
    else
      flash[:alert] = "Failed to join Event!"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @attendance = current_user.event_attendees.where(attended_event_id: event_params).first
    if @attendance.destroy
      flash[:notice] = "Successfully left Event!"
    else
      flash[:alert] = "Failed to leave Event!"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def event_params
    params.expect(:event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ "index", "show" ]
  before_action :set_event, only: %i[ edit update destroy ]
  before_action :event_params, only: %i[ create update ]
  def index
    @events = Event.all.includes(:attendees, :creator)
  end

  def show
    @event = Event.find(params[:id])
    unless @event.public_event? || user_signed_in? && (current_user.id == @event.creator.id || @event.attendee_ids.include?(current_user.id))
      redirect_to events_path
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(@filtered_params)
     if @event.save
      @event.attendees << current_user
      redirect_to @event
     else
      render :new, status: :unprocessable_entity
     end
  end

  def edit
  end

  def update
    redirect_to events_path unless @event.creator.id == current_user.id
    if @event.update(@filtered_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "Sucessfully deleted Event!"
    else
      flash[:alert] = "Failed to delete Event!"
    end
    redirect_to current_user
  end

  private
  def set_event
    @event = current_user.created_events.find(params[:id])
  end

  def event_params
    @filtered_params = params.expect(event: [ :location, :event_date, :visibility ])
    @filtered_params[:visibility] = @filtered_params[:visibility].to_i if @filtered_params.key?(:visibility)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :event_params
  before_action :validate_invitation, only: %i[ create ]
  def create
    @invitation = Invitation.build(invitation_event_id: @filtered_params[:event], invited_user_id: @filtered_params[:user].id)
    if @invitation.save
      flash[:notice] = "Invitation Sent!"
    else
      flash[:alert] = "Failed To Send Invitation!"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @invitation = current_user.invitations.where(invitation_event_id: @filtered_params[:event]).first
    if @invitation.destroy
      flash[:notice] = "Successfully Rejected Invitation!"
    else
      flash[:alert] = "Failed to Rejected Invitation!"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def event_params
    @filtered_params = params.expect(info: [ :user, :event ])
    @filtered_params[:user] = User.where(email: @filtered_params[:user]).first if @filtered_params.key?(:user)
    @filtered_params
  end

  def validate_invitation
    if !@filtered_params[:user] || current_user.id == @filtered_params[:user].id ||
      EventAttendee.where(attended_event_id: @filtered_params[:event], attendee_id: @filtered_params[:user]).exists?
        redirect_to events_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendee_helper.rb
module EventAttendeeHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div>
    <% if event.public_event? || user_signed_in? && (event.creator.id == current_user.id || event.attendee_ids.include?(current_user.id)) %>
        <% if user_signed_in? %>
            <% if !event.attendee_ids.include?(current_user.id)%>
                <%= button_to "Join Event", event_attendee_index_path , method: "post", params: {event: event.id}  %>
            <% else %>
                <%= button_to "Leave Event", event_attendee_path , method: "delete", params: {event: event.id}  %>
            <% end %>
        <% end %>
        <%= button_to "Show Event", event , method: "get", params: {event: event.id}  %>
        <h4><%= event.location %></h4>
        <div><%= event.event_date %></div>
    <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
    <div>
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div>
    <div>
        <%= form.label :event_date %>
        <%= form.date_field :event_date %>
    </div>
    <div>
        <%= form.label :visibility %>
        <%= form.select :visibility, [["Private", 0], ["Public", 1]] %>
    </div>
    <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<div>Edit Event</div>

<%= render "form", event: @event%>

app/views/events/index.html.erb
<% if !user_signed_in? %>
    <%= button_to "Log In", new_user_session_path, method: "get" %>
    <%= button_to "Sign Up", new_user_registration_path, method: "get" %>
<% end %>

<% if user_signed_in? %>
    <%= button_to "Create Event", new_event_path, method: "get"  %>
<% end %>
<h2>All Events</h2>
<%= render @events %>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
    <div>
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div>
    <div>
        <%= form.label :event_date %>
        <%= form.date_field :event_date %>
    </div>
    <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<div>
    <% if user_signed_in? %>
        <% if !@event.attendee_ids.include?(current_user.id)%>
            <%= button_to "Join Event", event_attendee_index_path , method: "post", params: {event: @event.id}  %>
        <% else %>
            <%= button_to "Leave Event", event_attendee_path , method: "delete", params: {event: @event.id}  %>
        <% end %>
        <% if current_user.id == @event.creator.id%>
                <%= form_with scope: :info, url: "/invitations", method: "post" do |form| %>
                    <div>
                        <%= form.label :user %>
                        <%= form.text_field :user %>
                    </div>
                    <%= form.hidden_field :event, value: @event.id %>
                    <%= form.submit %>
                <% end %>
            <%= button_to "Edit Event", edit_event_path(@event), method: "get" %>
            <%= button_to "Delete Event", @event , method: "delete", data: { turbo_confirm: "Are you sure?"} %>
            <% if @event.private_event?%>
                <%= button_to "Make Public", event_path(@event) , method: "patch", params: {event: {visibility: 1}}  %>
            <% else %>
                <%= button_to "Make Private", event_path(@event) , method: "patch", params: {event: {visibility: 0}}  %>
            <% end %>
        <% end %>
    <% end %>
    <h4><%= @event.location %></h4>
    <h5><%= @event.creator.username %> </h5>
    <div><%= @event.event_date %></div>
    <div>Created At: <%= @event.created_at %></div>
    <% @event.attendees.each do |attendee| %>
        <div><%= attendee.username %> </div>
    <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Private Events">
    <meta name="mobile-web-app-capable" content="yes">
     <meta name="turbo-refresh-method" content="morph">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to "Home", events_path %>
    <% if user_signed_in? %>
      <%= link_to "My Events", current_user %>
      <%= button_to "Log Out", destroy_user_session_path, method: "delete" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div>
    <div>Past Events</div>
    <%= render @user.attended_events.past %>
</div>
<div>
    <div>Future Events</div>
    <%= render @user.attended_events.future %>
</div>

<% if user_signed_in? %>
    <% current_user.invitations.each do |invitation| %>
        <li><%= invitation.invitation_event.location %></li>
        <%= button_to "Show Event", invitation.invitation_event , method: "get", params: {event: invitation.invitation_event.id}  %>
        <%= button_to "Accept", event_attendee_index_path , method: "post", params: {event: invitation.invitation_event.id}  %>
        <%= button_to "Reject", invitation_path , method: "delete", params: {info: {event: invitation.invitation_event.id}}  %>
      <% end %>
<% end %>